CREATE TABLE Student(
    NAME VARCHAR(30) PRIMARY KEY ,
    ADDRESS VARCHAR(100) NOT NULL ,
    CITY VARCHAR(20) NOT NULL ,
    COUNTRY VARCHAR(15) NOT NULL ,
    PINCODE NUMERIC NOT NULL ,
    SATSCORE DECIMAL NOT NULL ,
    PASSED VARCHAR(6) NOT NULL
);